server.port=8081



## H2 DB configuration proprties
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb 
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.data-locations=classpath:schema.sql,classpath:data.sql

#debug=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true

# JPA Settings
spring.jpa.hibernate.ddl-auto=update


# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


########  connect to H2 db console in chrome
##  url (chrome) = http://localhost:8083/h2-console
## 	JDBC URL (h2-console) = jdbc:h2:mem:testdb 



spring.messages.basename=messages
spring.messages.encoding=UTF-8

